#!/usr/bin/env bash
# Re-scans the Flutter project and regenerates .claude/PROJECT_MAP.md
# Run anytime: bash .claude/skills/scan-project/scan.sh
set -euo pipefail

DATE="$(date +%Y-%m-%d)"
OUT=".claude/PROJECT_MAP.md"

if [[ ! -d lib ]]; then
  echo "⚠️  No lib/ directory found. Run this from the Flutter project root."
  exit 1
fi

TREE="$(find lib -maxdepth 4 -type d | sort | tail -n +2 | awk -F/ '{
  indent="";
  for(i=2;i<NF;i++) indent = indent "  ";
  print indent "├── " $NF "/"
}')"

DEPS="(pubspec.yaml not found)"
if [[ -f pubspec.yaml ]]; then
  # Keep keys at exactly two spaces of indentation (top-level package names)
  # and ignore nested lines (for example, "  flutter:\n    sdk: flutter").
  DEPS="$(awk '/^dependencies:/{f=1;next}/^dev_dependencies:/{f=0}f' pubspec.yaml \
    | grep -E '^  [^ ]' \
    | sed -E 's/^  ([a-zA-Z0-9_.-]+):[[:space:]]*(.*)$/| \1 | \2 |/' || true)"
  [[ -z "$DEPS" ]] && DEPS="| _(none found)_ | |"
fi

PROVIDERS="$(grep -rl 'extends ChangeNotifier' lib --include='*.dart' 2>/dev/null | sort || true)"
if [[ -n "$PROVIDERS" ]]; then
  PROVIDERS_TABLE="$(echo "$PROVIDERS" | while read -r f; do
    name=$(grep -oE '[A-Za-z_]+ extends ChangeNotifier' "$f" | head -1 | awk '{print $1}')
    echo "| \`$name\` | \`$f\` |"
  done)"
else
  PROVIDERS_TABLE="| _(none found yet)_ | |"
fi

SCREENS="$(find lib \( -iname '*screen*.dart' -o -iname '*page*.dart' \) 2>/dev/null | sort || true)"
if [[ -n "$SCREENS" ]]; then
  SCREENS_TABLE="$(echo "$SCREENS" | while read -r f; do
    name=$(basename "$f" .dart)
    echo "| \`$name\` | \`$f\` |"
  done)"
else
  SCREENS_TABLE="| _(none found yet)_ | |"
fi

ROUTES="$(grep -rn "path:\s*['\"]" lib/core/router 2>/dev/null | sed -E "s/^([^:]+):([0-9]+):.*path:\s*['\"]([^'\"]+)['\"].*/| \3 | \1:\2 |/" || true)"
[[ -z "$ROUTES" ]] && ROUTES="| _(none found yet — check lib/core/router/)_ | |"

WIDGETS="$(find lib/shared/widgets -name '*.dart' 2>/dev/null | sort || true)"
if [[ -n "$WIDGETS" ]]; then
  WIDGETS_TABLE="$(echo "$WIDGETS" | while read -r f; do
    name=$(basename "$f" .dart)
    echo "| \`$name\` | \`$f\` |"
  done)"
else
  WIDGETS_TABLE="| _(none found yet)_ | |"
fi

FEATURES_TABLE="| _(none found yet)_ | | |"
if [[ -d lib/features ]]; then
  FEATURES_TABLE="$(find lib/features -maxdepth 1 -mindepth 1 -type d | sort | while read -r d; do
    name=$(basename "$d")
    has_domain=$([[ -d "$d/domain" ]] && echo "✓" || echo "—")
    has_data=$([[ -d "$d/data" ]] && echo "✓" || echo "—")
    has_pres=$([[ -d "$d/presentation" ]] && echo "✓" || echo "—")
    echo "| $name | \`$d\` | domain:$has_domain data:$has_data presentation:$has_pres |"
  done)"
fi

DART_COUNT="$(find lib -name '*.dart' 2>/dev/null | grep -vc '.g.dart\|.freezed.dart\|.mocks.dart' || true)"
[[ -n "$DART_COUNT" ]] || DART_COUNT="0"
PROVIDER_COUNT="$(printf '%s\n' "$PROVIDERS" | sed '/^$/d' | wc -l | tr -d ' ')"
FEATURE_COUNT="0"
if [[ -d lib/features ]]; then
  FEATURE_COUNT="$(find lib/features -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ')"
fi

cat > "$OUT" << MAPEOF
# PROJECT_MAP.md
> Generated: $DATE
> Source of truth for project structure. Regenerate anytime:
> \`bash .claude/skills/scan-project/scan.sh\`
> Do not hand-edit the generated tables — edit "Sensitive Areas" and "Change Log" only.

---

## Structure

\`\`\`
lib/
$TREE
\`\`\`

---

## Dependencies

| Package | Version |
|---|---|
$DEPS

---

## Features ($FEATURE_COUNT found)

| Feature | Path | Layers present |
|---|---|---|
$FEATURES_TABLE

---

## Providers ($PROVIDER_COUNT found)

| Provider | File |
|---|---|
$PROVIDERS_TABLE

---

## Screens

| Screen | File |
|---|---|
$SCREENS_TABLE

---

## Routes

| Path | Defined in |
|---|---|
$ROUTES

---

## Shared Widgets

| Widget | File |
|---|---|
$WIDGETS_TABLE

---

## Sensitive Areas
_(edit by hand — not overwritten by re-scan)_

| File / Folder | Why |
|---|---|
| \`lib/core/network/\` | Singleton Dio client — changes affect all API calls |
| \`lib/main.dart\` | Provider registration order matters |
| \`lib/core/router/\` | Route changes affect deep links and navigation |

---

## Change Log
_(edit by hand — not overwritten by re-scan)_

| Date | Change | Reason |
|---|---|---|
| $DATE | Initial scan | Generated by scan.sh |
MAPEOF

echo "✓ .claude/PROJECT_MAP.md regenerated"
echo "  Dart files: $DART_COUNT"
echo "  Features:   $FEATURE_COUNT"
echo "  Providers:  $PROVIDER_COUNT"
